// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRI4mdVQTRJq27S-XUlcZ0OYiez1JOM8I',
    appId: '1:620572428536:web:bd861fb0c5877ff257530d',
    messagingSenderId: '620572428536',
    projectId: 'elearning-app-a6fb4',
    authDomain: 'elearning-app-a6fb4.firebaseapp.com',
    storageBucket: 'elearning-app-a6fb4.appspot.com',
    measurementId: 'G-EGDPV8PBB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYpymjskXFvfEz8SrxJLjmMo7baV9CQKw',
    appId: '1:620572428536:android:c1b0eda11fa7416357530d',
    messagingSenderId: '620572428536',
    projectId: 'elearning-app-a6fb4',
    storageBucket: 'elearning-app-a6fb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5lr0AO6WOwqzrm8cyDKe0cF6N0qejOE',
    appId: '1:620572428536:ios:6f2d7b2a71e5a6ab57530d',
    messagingSenderId: '620572428536',
    projectId: 'elearning-app-a6fb4',
    storageBucket: 'elearning-app-a6fb4.appspot.com',
    iosBundleId: 'ptit.trungng.eLearningApp',
  );
}
